...
try{
assertTrue(condition);
}

catch (SomeException e)
        {
            fail("exception = " + e.getReason());
        }
...